# include: package:lint/analysis_options.yaml

# analyzer:
#   exclude:
#     - "lib/presentation/localization/**"
#     - "lib/data/models/**"
#   errors:
#     missing_required_param: error

# linter:
#   rules:
#     avoid_classes_with_only_static_members: false