name: flutter_next_weather
description: A Flutter weather application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  intl: ^0.16.1
  kiwi: ^2.0.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.4
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  bloc_test: ^7.0.4
  lint: ^1.2.0
  linter: ^0.1.118

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - resources/fonts/
    - resources/graphics/
    - resources/graphics/images/
    - resources/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: resources/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: resources/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: resources/fonts/Roboto-Light.ttf
          weight: 300
        - asset: resources/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: resources/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: resources/fonts/Roboto-Italic.ttf
          style: italic
        - asset: resources/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: resources/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: resources/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: resources/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: resources/fonts/Roboto-Black.ttf
          weight: 900
        - asset: resources/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

